### PR TITLE
Restructure project

### PR DESCRIPTION
**Pull request by chornerman**
## What happened 👀

From @sleepylee [suggestion](https://github.com/nimblehq/github-action-runner-android/pull/15#issuecomment-902419692), we have to restructure this project so that it's become a regular project and not a container of multiple projects.
 
## Insight 📝

Running a script to generate a new project from the RxJava template and modified it to link to this repository.
 
## Proof Of Work 📹

Able to run both `staging` and `production` correctly.

### CODE REVIEW

**Comment by sleepylee** [comment]
- please make sure that it passes the CI (with our custom runner)
- please update the CODEOWNER file to include only the people who involve in this project.

image

**Comment by chornerman** [comment]
@sleepylee Codeowners edited and all checks are passed 🙏🏼

**Comment by lydiasama** [comment]
@chornerman Have you started the runner? It seems CI still hasn't worked.

**Review by lydiasama — APPROVED** [review]
LGTM

**Pull request merged**
